# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
board: [ "nice_nano_v2" ]
shield: [ "corne_left", "corne_right", "tbkmini_left", "tbkmini_right" ]
cmake-args: [ "-DKEYMAP_FILE=../../config/6x3-3.keymap" ]
include:
  - board: "nice_nano_v2"
    shield: corne_left
    # snippet: "choc-sunset"
    # artifact-name: corne_left-choc_sunset
  - board: "nice_nano_v2"
    shield: corne_right
    # snippet: "choc-sunset"
    # artifact-name: corne_right-choc_sunset
  - board: "nice_nano_v2"
    shield: tbkmini_left
    # snippet: "gazzew-u4-silent-tactile"
    # artifact-name: tbkmini_left-gazzew_silent
  - board: "nice_nano_v2"
    shield: tbkmini_right
    # snippet: "gazzew-u4-silent-tactile"
    # artifact-name: tbkmini_right-gazzew_silent
  - board: "nice_nano_v2"
    shield: settings_reset
  
